name = "fs"
compatibility_date = "2023-01-01"
main = "src/index.ts"

workers_dev = false # INSECURE, DO NOT ENABLE
route = { pattern = "up.stele.site", custom_domain = true } # CHANGEME

[site]
bucket = "./assets"

[vars]
PUBLIC_BUCKET_URL = "https://fs.stele.site" # CHANGEME
R2_BUCKET_NAME = "personal" # CHANGEME
CF_ACCOUNT_ID = "a915d3db9633acaff21beeb923012a4e" # CHANGEME

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "personal" # CHANGEME
preview_bucket_name = "personal" # CHANGEME (optional, for development)
